/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AdminController;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.Diem;
import model.SinhVien;
import model.GiangVien;
import model.HocPhan;
import model.LopHoc;

public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Admin() {
        initComponents();
        init();
    }

    public void init() {
        this.adminController = new AdminController();
        this.hienThiSinhVien();
        this.hienThiGiangVien();
        this.hienThiHocPhan();
        this.hienThiLopHoc();
        this.hienThiDiem();
        ActionListener action = new AdminController(this);
        this.jButton_suaDiem.addActionListener(action);
        this.jButton_suaGiangVien.addActionListener(action);
        this.jButton_suaHocPhan.addActionListener(action);
        this.jButton_suaLopHoc.addActionListener(action);
        this.jButton_suaSinhVien.addActionListener(action);
        this.jButton_themMoiDiem.addActionListener(action);
        this.jButton_themMoiGiangVien.addActionListener(action);
        this.jButton_themMoiHocPhan.addActionListener(action);
        this.jButton_themMoiLopHoc.addActionListener(action);
        this.jButton_themMoiSinhVien.addActionListener(action);
        this.jButton_timKiemDiem.addActionListener(action);
        this.jButton_timKiemGiangVien.addActionListener(action);
        this.jButton_timKiemHocPhan.addActionListener(action);
        this.jButton_timKiemLopHoc.addActionListener(action);
        this.jButton_timKiemSinhVien.addActionListener(action);
        this.jButton_xoaDiem.addActionListener(action);
        this.jButton_xoaGiangVien.addActionListener(action);
        this.jButton_xoaHocPhan.addActionListener(action);
        this.jButton_xoaLopHoc.addActionListener(action);
        this.jButton_xoaSinhVien.addActionListener(action);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_TuKhoaSinhVien = new javax.swing.JTextField();
        jButton_timKiemSinhVien = new javax.swing.JButton();
        jButton_themMoiSinhVien = new javax.swing.JButton();
        jButton_suaSinhVien = new javax.swing.JButton();
        jButton_xoaSinhVien = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_TimKiemSinhVien = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_SinhVien = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_TuKhoaGiangVien = new javax.swing.JTextField();
        jButton_timKiemGiangVien = new javax.swing.JButton();
        jButton_themMoiGiangVien = new javax.swing.JButton();
        jButton_suaGiangVien = new javax.swing.JButton();
        jButton_xoaGiangVien = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_TimKiemGiangVien = new javax.swing.JComboBox<>();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable_GiangVien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_TuKhoaHocPhan = new javax.swing.JTextField();
        jButton_timKiemHocPhan = new javax.swing.JButton();
        jButton_themMoiHocPhan = new javax.swing.JButton();
        jButton_suaHocPhan = new javax.swing.JButton();
        jButton_xoaHocPhan = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_HocPhan = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_TimKiemHocPhan = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_TuKhoaLopHoc = new javax.swing.JTextField();
        jButton_timKiemLopHoc = new javax.swing.JButton();
        jButton_themMoiLopHoc = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable_LopHoc = new javax.swing.JTable();
        jButton_suaLopHoc = new javax.swing.JButton();
        jButton_xoaLopHoc = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_TimKiemLopHoc = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_TuKhoaDiem = new javax.swing.JTextField();
        jButton_timKiemDiem = new javax.swing.JButton();
        jButton_themMoiDiem = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable_Diem = new javax.swing.JTable();
        jButton_suaDiem = new javax.swing.JButton();
        jButton_xoaDiem = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_TimKiemDiem = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Từ khoá");

        jButton_timKiemSinhVien.setText("Tìm kiếm sinh viên");

        jButton_themMoiSinhVien.setText("Thêm mới sinh viên");
        jButton_themMoiSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_themMoiSinhVienActionPerformed(evt);
            }
        });

        jButton_suaSinhVien.setText("Sửa sinh viên");

        jButton_xoaSinhVien.setText("Xoá sinh viên");

        jLabel7.setText("Tìm kiếm theo");

        jComboBox_TimKiemSinhVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MSSV", "HoTen" }));

        jTable_SinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSSV", "Họ tên", "Giới tính", "Ngày sinh", "SĐT", "Quê quán", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_SinhVien);
        if (jTable_SinhVien.getColumnModel().getColumnCount() > 0) {
            jTable_SinhVien.getColumnModel().getColumn(0).setResizable(false);
            jTable_SinhVien.getColumnModel().getColumn(1).setResizable(false);
            jTable_SinhVien.getColumnModel().getColumn(2).setResizable(false);
            jTable_SinhVien.getColumnModel().getColumn(3).setResizable(false);
            jTable_SinhVien.getColumnModel().getColumn(4).setResizable(false);
            jTable_SinhVien.getColumnModel().getColumn(5).setResizable(false);
            jTable_SinhVien.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_TuKhoaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_TimKiemSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(306, 306, 306)
                                .addComponent(jButton_timKiemSinhVien))
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_suaSinhVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_themMoiSinhVien, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_xoaSinhVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_TuKhoaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox_TimKiemSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_timKiemSinhVien)
                    .addComponent(jButton_themMoiSinhVien))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_suaSinhVien)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_xoaSinhVien)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("QL Sinh Viên", jPanel1);

        jLabel2.setText("Từ khoá");

        jButton_timKiemGiangVien.setText("Tìm kiếm giảng viên");

        jButton_themMoiGiangVien.setText("Thêm mới giảng viên");

        jButton_suaGiangVien.setText("Sửa giảng viên");

        jButton_xoaGiangVien.setText("Xoá giảng viên");
        jButton_xoaGiangVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xoaGiangVienActionPerformed(evt);
            }
        });

        jLabel8.setText("Tìm kiếm theo");

        jComboBox_TimKiemGiangVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MSGV", "HoTen" }));

        jTable_GiangVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSGV", "Họ tên", "Giới tính", "Ngày sinh", "Quên quán", "SĐT", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane13.setViewportView(jTable_GiangVien);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_TuKhoaGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_TimKiemGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                        .addComponent(jButton_timKiemGiangVien))
                    .addComponent(jScrollPane13))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_themMoiGiangVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_suaGiangVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_xoaGiangVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_TuKhoaGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jComboBox_TimKiemGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_timKiemGiangVien)
                        .addComponent(jButton_themMoiGiangVien)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_suaGiangVien)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_xoaGiangVien))
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("QL Giảng Viên", jPanel2);

        jLabel3.setText("Từ khoá");

        jButton_timKiemHocPhan.setText("Tìm kiếm học phần");
        jButton_timKiemHocPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_timKiemHocPhanActionPerformed(evt);
            }
        });

        jButton_themMoiHocPhan.setText("Thêm mới học phần");

        jButton_suaHocPhan.setText("Sửa học phần");

        jButton_xoaHocPhan.setText("Xoá học phần");

        jTable_HocPhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã học phần", "Tên học phần", "Số tín chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable_HocPhan);
        if (jTable_HocPhan.getColumnModel().getColumnCount() > 0) {
            jTable_HocPhan.getColumnModel().getColumn(0).setResizable(false);
            jTable_HocPhan.getColumnModel().getColumn(1).setResizable(false);
            jTable_HocPhan.getColumnModel().getColumn(2).setResizable(false);
        }

        jScrollPane5.setViewportView(jScrollPane4);

        jLabel9.setText("Tìm kiếm theo");

        jComboBox_TimKiemHocPhan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MaHP", "TenHP" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_TuKhoaHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_TimKiemHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(jButton_timKiemHocPhan))
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_themMoiHocPhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_suaHocPhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_xoaHocPhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_TuKhoaHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox_TimKiemHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_timKiemHocPhan)
                    .addComponent(jButton_themMoiHocPhan))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton_suaHocPhan)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_xoaHocPhan)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("QL Học Phần", jPanel3);

        jLabel4.setText("Từ khoá");

        jButton_timKiemLopHoc.setText("Tìm kiếm lớp học");

        jButton_themMoiLopHoc.setText("Thêm mới lớp học");

        jTable_LopHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã lớp", "Mã học phần", "MSGV", "Phòng học", "Thời gian"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable_LopHoc);
        if (jTable_LopHoc.getColumnModel().getColumnCount() > 0) {
            jTable_LopHoc.getColumnModel().getColumn(0).setResizable(false);
            jTable_LopHoc.getColumnModel().getColumn(1).setResizable(false);
            jTable_LopHoc.getColumnModel().getColumn(2).setResizable(false);
            jTable_LopHoc.getColumnModel().getColumn(3).setResizable(false);
            jTable_LopHoc.getColumnModel().getColumn(4).setResizable(false);
        }

        jScrollPane7.setViewportView(jScrollPane6);

        jButton_suaLopHoc.setText("Sửa lớp học");

        jButton_xoaLopHoc.setText("Xoá lớp học");

        jLabel6.setText("Tìm kiếm theo");

        jComboBox_TimKiemLopHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MaLop", "MaHP", "MSGV" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(29, 29, 29)
                        .addComponent(jTextField_TuKhoaLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6)
                        .addGap(52, 52, 52)
                        .addComponent(jComboBox_TimKiemLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_timKiemLopHoc))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton_xoaLopHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_suaLopHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton_themMoiLopHoc, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_timKiemLopHoc)
                            .addComponent(jButton_themMoiLopHoc)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_TuKhoaLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4))
                            .addComponent(jComboBox_TimKiemLopHoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton_suaLopHoc)
                        .addGap(85, 85, 85)
                        .addComponent(jButton_xoaLopHoc)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("QL Lớp Học", jPanel4);

        jLabel5.setText("Từ khoá");

        jButton_timKiemDiem.setText("Tìm kiếm điểm");

        jButton_themMoiDiem.setText("Thêm mới điểm");

        jTable_Diem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã lớp", "Mã học phần", "MSSV", "Điểm QT", "Điểm CK", "Trọng số"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTable_Diem);
        if (jTable_Diem.getColumnModel().getColumnCount() > 0) {
            jTable_Diem.getColumnModel().getColumn(0).setResizable(false);
            jTable_Diem.getColumnModel().getColumn(1).setResizable(false);
            jTable_Diem.getColumnModel().getColumn(2).setResizable(false);
            jTable_Diem.getColumnModel().getColumn(3).setResizable(false);
            jTable_Diem.getColumnModel().getColumn(4).setResizable(false);
            jTable_Diem.getColumnModel().getColumn(5).setResizable(false);
        }

        jScrollPane9.setViewportView(jScrollPane8);

        jButton_suaDiem.setText("Sửa điểm");

        jButton_xoaDiem.setText("Xoá điểm");

        jLabel10.setText("Tìm kiếm theo");

        jComboBox_TimKiemDiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MaLop", "MaHP", "MSSV" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_TuKhoaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_TimKiemDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addComponent(jButton_timKiemDiem))
                    .addComponent(jScrollPane9))
                .addGap(90, 90, 90)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton_suaDiem, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addComponent(jButton_xoaDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton_themMoiDiem))
                .addGap(121, 121, 121))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jButton_themMoiDiem)
                .addGap(101, 101, 101)
                .addComponent(jButton_suaDiem)
                .addGap(66, 66, 66)
                .addComponent(jButton_xoaDiem)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_TuKhoaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox_TimKiemDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_timKiemDiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("QL Điểm", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_xoaGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xoaGiangVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_xoaGiangVienActionPerformed

    private void jButton_themMoiSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_themMoiSinhVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_themMoiSinhVienActionPerformed

    private void jButton_timKiemHocPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_timKiemHocPhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_timKiemHocPhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    public void hienThiSinhVien() {
        ArrayList<SinhVien> listSinhVien = this.adminController.hienThiSinhVien();
        DefaultTableModel model = (DefaultTableModel) jTable_SinhVien.getModel();
        model.setRowCount(0);
        for (SinhVien sv : listSinhVien) {
            Object[] row = {
                sv.getMSSV(),
                sv.getHoTen(),
                sv.getGioiTinh(),
                sv.getNgaySinh(),
                sv.getQueQuan(),
                sv.getSDT(),
                sv.getEmail()
            };
            model.addRow(row);
        }
    }

    public void hienThiGiangVien() {
        ArrayList<GiangVien> listGiangVien = this.adminController.hienThiGiangVien();
        DefaultTableModel model = (DefaultTableModel) jTable_GiangVien.getModel();
        model.setRowCount(0);
        for (GiangVien gv : listGiangVien) {
            Object[] row = {
                gv.getMSGV(),
                gv.getHoTen(),
                gv.getGioiTinh(),
                gv.getNgaySinh(),
                gv.getQueQuan(),
                gv.getSDT(),
                gv.getEmail()
            };
            model.addRow(row);
        }
    }

    public void hienThiDiem() {
        ArrayList<Diem> listDiem = this.adminController.hienThiDiem();
        DefaultTableModel model = (DefaultTableModel) jTable_Diem.getModel();
        model.setRowCount(0);
        for (Diem diem : listDiem) {
            Object[] row = {
                diem.getMaLop(),
                diem.getMaHP(),
                diem.getMSSV(),
                diem.getDiemQT(),
                diem.getDiemCK(),
                diem.getTrongSoQT()
            };
            model.addRow(row);
        }
    }

    public void hienThiLopHoc() {
        ArrayList<LopHoc> listLopHoc = this.adminController.hienThiLopHoc();
        DefaultTableModel model = (DefaultTableModel) jTable_LopHoc.getModel();
        model.setRowCount(0);
        for (LopHoc lopHoc : listLopHoc) {
            Object[] row = {
                lopHoc.getMaLop(),
                lopHoc.getMaHP(),
                lopHoc.getMSGV(),
                lopHoc.getPhongHoc(),
                lopHoc.getThoiGian()
            };
            model.addRow(row);
        }
    }

    public void hienThiHocPhan() {
        ArrayList<HocPhan> listHocPhan = this.adminController.hienThiHocPhan();
        DefaultTableModel model = (DefaultTableModel) jTable_HocPhan.getModel();
        model.setRowCount(0);
        for (HocPhan hocPhan : listHocPhan) {
            Object[] row = {
                hocPhan.getMaHP(),
                hocPhan.getTenHP(),
                hocPhan.getSoTinChi()
            };
            model.addRow(row);
        }
    }

    public void timKiemSinhVien(ArrayList<SinhVien> listSinhVien) {
        DefaultTableModel model = (DefaultTableModel) jTable_SinhVien.getModel();
        model.setRowCount(0);
        for (SinhVien sv : listSinhVien) {
            Object[] row = {
                sv.getMSSV(),
                sv.getHoTen(),
                sv.getGioiTinh(),
                sv.getNgaySinh(),
                sv.getQueQuan(),
                sv.getSDT(),
                sv.getEmail()
            };
            model.addRow(row);
        }
    }

    public void timKiemGiangVien(ArrayList<GiangVien> listGiangVien) {
        DefaultTableModel model = (DefaultTableModel) jTable_GiangVien.getModel();
        model.setRowCount(0);
        for (GiangVien gv : listGiangVien) {
            Object[] row = {
                gv.getMSGV(),
                gv.getHoTen(),
                gv.getGioiTinh(),
                gv.getNgaySinh(),
                gv.getQueQuan(),
                gv.getSDT(),
                gv.getEmail()
            };
            model.addRow(row);
        }
    }

    public void timKiemHocPhan(ArrayList<HocPhan> listHocPhan) {
        DefaultTableModel model = (DefaultTableModel) jTable_HocPhan.getModel();
        model.setRowCount(0);
        for (HocPhan hocPhan : listHocPhan) {
            Object[] row = {
                hocPhan.getMaHP(),
                hocPhan.getTenHP(),
                hocPhan.getSoTinChi()
            };
            model.addRow(row);
        }
    }

    public void timKiemLopHoc(ArrayList<LopHoc> listLopHoc) {
        DefaultTableModel model = (DefaultTableModel) jTable_LopHoc.getModel();
        model.setRowCount(0);
        for (LopHoc lopHoc : listLopHoc) {
            Object[] row = {
                lopHoc.getMaLop(),
                lopHoc.getMaHP(),
                lopHoc.getMSGV(),
                lopHoc.getPhongHoc(),
                lopHoc.getThoiGian()
            };
            model.addRow(row);
        }
    }

    public void timKiemDiem(ArrayList<Diem> listDiem) {
        DefaultTableModel model = (DefaultTableModel) jTable_Diem.getModel();
        model.setRowCount(0);
        for (Diem diem : listDiem) {
            Object[] row = {
                diem.getMaLop(),
                diem.getMaHP(),
                diem.getMSSV(),
                diem.getDiemQT(),
                diem.getDiemCK(),
                diem.getTrongSoQT()
            };
            model.addRow(row);
        }
    }
    private AdminController adminController;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_suaDiem;
    private javax.swing.JButton jButton_suaGiangVien;
    private javax.swing.JButton jButton_suaHocPhan;
    private javax.swing.JButton jButton_suaLopHoc;
    private javax.swing.JButton jButton_suaSinhVien;
    private javax.swing.JButton jButton_themMoiDiem;
    private javax.swing.JButton jButton_themMoiGiangVien;
    private javax.swing.JButton jButton_themMoiHocPhan;
    private javax.swing.JButton jButton_themMoiLopHoc;
    private javax.swing.JButton jButton_themMoiSinhVien;
    private javax.swing.JButton jButton_timKiemDiem;
    private javax.swing.JButton jButton_timKiemGiangVien;
    private javax.swing.JButton jButton_timKiemHocPhan;
    private javax.swing.JButton jButton_timKiemLopHoc;
    private javax.swing.JButton jButton_timKiemSinhVien;
    private javax.swing.JButton jButton_xoaDiem;
    private javax.swing.JButton jButton_xoaGiangVien;
    private javax.swing.JButton jButton_xoaHocPhan;
    private javax.swing.JButton jButton_xoaLopHoc;
    private javax.swing.JButton jButton_xoaSinhVien;
    private javax.swing.JComboBox<String> jComboBox_TimKiemDiem;
    private javax.swing.JComboBox<String> jComboBox_TimKiemGiangVien;
    private javax.swing.JComboBox<String> jComboBox_TimKiemHocPhan;
    private javax.swing.JComboBox<String> jComboBox_TimKiemLopHoc;
    private javax.swing.JComboBox<String> jComboBox_TimKiemSinhVien;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_Diem;
    private javax.swing.JTable jTable_GiangVien;
    private javax.swing.JTable jTable_HocPhan;
    private javax.swing.JTable jTable_LopHoc;
    private javax.swing.JTable jTable_SinhVien;
    private javax.swing.JTextField jTextField_TuKhoaDiem;
    private javax.swing.JTextField jTextField_TuKhoaGiangVien;
    private javax.swing.JTextField jTextField_TuKhoaHocPhan;
    private javax.swing.JTextField jTextField_TuKhoaLopHoc;
    private javax.swing.JTextField jTextField_TuKhoaSinhVien;
    // End of variables declaration//GEN-END:variables

    public JTable getjTable_Diem() {
        return jTable_Diem;
    }

    public void setjTable_Diem(JTable jTable_Diem) {
        this.jTable_Diem = jTable_Diem;
    }

    public JTable getjTable_GiangVien() {
        return jTable_GiangVien;
    }

    public void setjTable_GiangVien(JTable jTable_GiangVien) {
        this.jTable_GiangVien = jTable_GiangVien;
    }

    public JTable getjTable_HocPhan() {
        return jTable_HocPhan;
    }

    public void setjTable_HocPhan(JTable jTable_HocPhan) {
        this.jTable_HocPhan = jTable_HocPhan;
    }

    public JTable getjTable_LopHoc() {
        return jTable_LopHoc;
    }

    public void setjTable_LopHoc(JTable jTable_LopHoc) {
        this.jTable_LopHoc = jTable_LopHoc;
    }

    public JTable getjTable_SinhVien() {
        return jTable_SinhVien;
    }

    public void setjTable_SinhVien(JTable jTable_SinhVien) {
        this.jTable_SinhVien = jTable_SinhVien;
    }

    public JComboBox<String> getjComboBox_TimKiemDiem() {
        return jComboBox_TimKiemDiem;
    }

    public void setjComboBox_TimKiemDiem(JComboBox<String> jComboBox_TimKiemDiem) {
        this.jComboBox_TimKiemDiem = jComboBox_TimKiemDiem;
    }

    public JComboBox<String> getjComboBox_TimKiemGiangVien() {
        return jComboBox_TimKiemGiangVien;
    }

    public void setjComboBox_TimKiemGiangVien(JComboBox<String> jComboBox_TimKiemGiangVien) {
        this.jComboBox_TimKiemGiangVien = jComboBox_TimKiemGiangVien;
    }

    public JComboBox<String> getjComboBox_TimKiemHocPhan() {
        return jComboBox_TimKiemHocPhan;
    }

    public void setjComboBox_TimKiemHocPhan(JComboBox<String> jComboBox_TimKiemHocPhan) {
        this.jComboBox_TimKiemHocPhan = jComboBox_TimKiemHocPhan;
    }

    public JComboBox<String> getjComboBox_TimKiemLopHoc() {
        return jComboBox_TimKiemLopHoc;
    }

    public void setjComboBox_TimKiemLopHoc(JComboBox<String> jComboBox_TimKiemLopHoc) {
        this.jComboBox_TimKiemLopHoc = jComboBox_TimKiemLopHoc;
    }

    public JComboBox<String> getjComboBox_TimKiemSinhVien() {
        return jComboBox_TimKiemSinhVien;
    }

    public void setjComboBox_TimKiemSinhVien(JComboBox<String> jComboBox_TimKiemSinhVien) {
        this.jComboBox_TimKiemSinhVien = jComboBox_TimKiemSinhVien;
    }

    public JTextField getjTextField_TuKhoaDiem() {
        return jTextField_TuKhoaDiem;
    }

    public void setjTextField_TuKhoaDiem(JTextField jTextField_TuKhoaDiem) {
        this.jTextField_TuKhoaDiem = jTextField_TuKhoaDiem;
    }

    public JTextField getjTextField_TuKhoaGiangVien() {
        return jTextField_TuKhoaGiangVien;
    }

    public void setjTextField_TuKhoaGiangVien(JTextField jTextField_TuKhoaGiangVien) {
        this.jTextField_TuKhoaGiangVien = jTextField_TuKhoaGiangVien;
    }

    public JTextField getjTextField_TuKhoaHocPhan() {
        return jTextField_TuKhoaHocPhan;
    }

    public void setjTextField_TuKhoaHocPhan(JTextField jTextField_TuKhoaHocPhan) {
        this.jTextField_TuKhoaHocPhan = jTextField_TuKhoaHocPhan;
    }

    public JTextField getjTextField_TuKhoaLopHoc() {
        return jTextField_TuKhoaLopHoc;
    }

    public void setjTextField_TuKhoaLopHoc(JTextField jTextField_TuKhoaLopHoc) {
        this.jTextField_TuKhoaLopHoc = jTextField_TuKhoaLopHoc;
    }

    public JTextField getjTextField_TuKhoaSinhVien() {
        return jTextField_TuKhoaSinhVien;
    }

    public void setjTextField_TuKhoaSinhVien(JTextField jTextField_TuKhoaSinhVien) {
        this.jTextField_TuKhoaSinhVien = jTextField_TuKhoaSinhVien;
    }

}
