/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AdminController;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.Diem;
import model.SinhVien;
import model.GiangVien;
import model.HocPhan;
import model.LopHoc;

/**
 *
 * @author nnminh322
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Admin() {
        initComponents();
        init();
    }

    public void init() {
        this.adminController = new AdminController();
        this.hienThiSinhVien();
        this.hienThiGiangVien();
        this.hienThiHocPhan();
        this.hienThiLopHoc();
        this.hienThiDiem();
        ActionListener action = new AdminController(this);
        this.jButton_suaDiem.addActionListener(action);
        this.jButton_suaGiangVien.addActionListener(action);
        this.jButton_suaHocPhan.addActionListener(action);
        this.jButton_suaLopHoc.addActionListener(action);
        this.jButton_suaSinhVien.addActionListener(action);
        this.jButton_themMoiDiem.addActionListener(action);
        this.jButton_themMoiGiangVien.addActionListener(action);
        this.jButton_themMoiHocPhan.addActionListener(action);
        this.jButton_themMoiLopHoc.addActionListener(action);
        this.jButton_themMoiSinhVien.addActionListener(action);
        this.jButton_timKiemDiem.addActionListener(action);
        this.jButton_timKiemGiangVien.addActionListener(action);
        this.jButton_timKiemHocPhan.addActionListener(action);
        this.jButton_timKiemLopHoc.addActionListener(action);
        this.jButton_timKiemSinhVien.addActionListener(action);
        this.jButton_xoaDiem.addActionListener(action);
        this.jButton_xoaGiangVien.addActionListener(action);
        this.jButton_xoaHocPhan.addActionListener(action);
        this.jButton_xoaLopHoc.addActionListener(action);
        this.jButton_xoaSinhVien.addActionListener(action);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton_timKiemSinhVien = new javax.swing.JButton();
        jButton_themMoiSinhVien = new javax.swing.JButton();
        jButton_suaSinhVien = new javax.swing.JButton();
        jButton_xoaSinhVien = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_SinhVien = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton_timKiemGiangVien = new javax.swing.JButton();
        jButton_themMoiGiangVien = new javax.swing.JButton();
        jButton_suaGiangVien = new javax.swing.JButton();
        jButton_xoaGiangVien = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable_GiangVien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton_timKiemHocPhan = new javax.swing.JButton();
        jButton_themMoiHocPhan = new javax.swing.JButton();
        jButton_suaHocPhan = new javax.swing.JButton();
        jButton_xoaHocPhan = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_HocPhan = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton_timKiemLopHoc = new javax.swing.JButton();
        jButton_themMoiLopHoc = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable_LopHoc = new javax.swing.JTable();
        jButton_suaLopHoc = new javax.swing.JButton();
        jButton_xoaLopHoc = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton_timKiemDiem = new javax.swing.JButton();
        jButton_themMoiDiem = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable_Diem = new javax.swing.JTable();
        jButton_suaDiem = new javax.swing.JButton();
        jButton_xoaDiem = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Từ khoá");

        jButton_timKiemSinhVien.setText("Tìm kiếm sinh viên");

        jButton_themMoiSinhVien.setText("Thêm mới sinh viên");
        jButton_themMoiSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_themMoiSinhVienActionPerformed(evt);
            }
        });

        jButton_suaSinhVien.setText("Sửa sinh viên");

        jButton_xoaSinhVien.setText("Xoá sinh viên");

        jTable_SinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSSV", "Họ tên", "Giới tính", "Ngày sinh", "SĐT", "Quê quán", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_SinhVien);
        if (jTable_SinhVien.getColumnModel().getColumnCount() > 0) {
            jTable_SinhVien.getColumnModel().getColumn(0).setResizable(false);
            jTable_SinhVien.getColumnModel().getColumn(1).setResizable(false);
            jTable_SinhVien.getColumnModel().getColumn(2).setResizable(false);
            jTable_SinhVien.getColumnModel().getColumn(3).setResizable(false);
            jTable_SinhVien.getColumnModel().getColumn(4).setResizable(false);
            jTable_SinhVien.getColumnModel().getColumn(5).setResizable(false);
            jTable_SinhVien.getColumnModel().getColumn(6).setResizable(false);
        }

        jScrollPane11.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel1)
                        .addGap(80, 80, 80)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jButton_timKiemSinhVien)
                        .addGap(32, 32, 32)
                        .addComponent(jButton_themMoiSinhVien))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_suaSinhVien)
                    .addComponent(jButton_xoaSinhVien))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_timKiemSinhVien, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_themMoiSinhVien, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(95, 95, 95)
                .addComponent(jButton_suaSinhVien)
                .addGap(89, 89, 89)
                .addComponent(jButton_xoaSinhVien)
                .addGap(57, 338, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("QL Sinh Viên", jPanel1);

        jLabel2.setText("Từ khoá");

        jButton_timKiemGiangVien.setText("Tìm kiếm giảng viên");

        jButton_themMoiGiangVien.setText("Thêm mới giảng viên");

        jButton_suaGiangVien.setText("Sửa giảng viên");

        jButton_xoaGiangVien.setText("Xoá giảng viên");
        jButton_xoaGiangVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xoaGiangVienActionPerformed(evt);
            }
        });

        jTable_GiangVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSGV", "Họ tên", "Giới tính", "Ngày sinh", "Quên quán", "SĐT", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane13.setViewportView(jTable_GiangVien);

        jScrollPane14.setViewportView(jScrollPane13);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel2)
                .addGap(92, 92, 92)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jButton_timKiemGiangVien)
                .addGap(80, 80, 80)
                .addComponent(jButton_themMoiGiangVien)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane14)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_suaGiangVien)
                    .addComponent(jButton_xoaGiangVien))
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_timKiemGiangVien)
                    .addComponent(jButton_themMoiGiangVien))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButton_suaGiangVien)
                        .addGap(90, 90, 90)
                        .addComponent(jButton_xoaGiangVien)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("QL Giảng Viên", jPanel2);

        jLabel3.setText("Từ khoá");

        jButton_timKiemHocPhan.setText("Tìm kiếm học phần");
        jButton_timKiemHocPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_timKiemHocPhanActionPerformed(evt);
            }
        });

        jButton_themMoiHocPhan.setText("Thêm mới học phần");

        jButton_suaHocPhan.setText("Sửa học phần");

        jButton_xoaHocPhan.setText("Xoá học phần");

        jTable_HocPhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã học phần", "Tên học phần", "Số tín chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable_HocPhan);
        if (jTable_HocPhan.getColumnModel().getColumnCount() > 0) {
            jTable_HocPhan.getColumnModel().getColumn(0).setResizable(false);
            jTable_HocPhan.getColumnModel().getColumn(1).setResizable(false);
            jTable_HocPhan.getColumnModel().getColumn(2).setResizable(false);
        }

        jScrollPane5.setViewportView(jScrollPane4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jLabel3)
                .addGap(86, 86, 86)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton_timKiemHocPhan)
                .addGap(49, 49, 49)
                .addComponent(jButton_themMoiHocPhan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_suaHocPhan)
                    .addComponent(jButton_xoaHocPhan))
                .addGap(80, 80, 80))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_timKiemHocPhan)
                    .addComponent(jButton_themMoiHocPhan))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButton_suaHocPhan)
                        .addGap(61, 61, 61)
                        .addComponent(jButton_xoaHocPhan)
                        .addGap(252, 252, 252))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("QL Học Phần", jPanel3);

        jLabel4.setText("Từ khoá");

        jButton_timKiemLopHoc.setText("Tìm kiếm lớp học");

        jButton_themMoiLopHoc.setText("Thêm mới lớp học");

        jTable_LopHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã lớp", "Mã học phần", "MSGV", "Phòng học", "Thời gian"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable_LopHoc);
        if (jTable_LopHoc.getColumnModel().getColumnCount() > 0) {
            jTable_LopHoc.getColumnModel().getColumn(0).setResizable(false);
            jTable_LopHoc.getColumnModel().getColumn(1).setResizable(false);
            jTable_LopHoc.getColumnModel().getColumn(2).setResizable(false);
            jTable_LopHoc.getColumnModel().getColumn(3).setResizable(false);
            jTable_LopHoc.getColumnModel().getColumn(4).setResizable(false);
        }

        jScrollPane7.setViewportView(jScrollPane6);

        jButton_suaLopHoc.setText("Sửa lớp học");

        jButton_xoaLopHoc.setText("Xoá lớp học");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel4)
                        .addGap(111, 111, 111)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jButton_timKiemLopHoc)
                        .addGap(67, 67, 67)
                        .addComponent(jButton_themMoiLopHoc))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_suaLopHoc)
                            .addComponent(jButton_xoaLopHoc))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_timKiemLopHoc)
                    .addComponent(jButton_themMoiLopHoc))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton_suaLopHoc)
                        .addGap(89, 89, 89)
                        .addComponent(jButton_xoaLopHoc)
                        .addContainerGap(317, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("QL Lớp Học", jPanel4);

        jLabel5.setText("Từ khoá");

        jButton_timKiemDiem.setText("Tìm kiếm điểm");

        jButton_themMoiDiem.setText("Thêm mới điểm");

        jTable_Diem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã lớp", "Mã học phần", "MSSV", "Điểm QT", "Điểm CK", "Trọng số"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTable_Diem);
        if (jTable_Diem.getColumnModel().getColumnCount() > 0) {
            jTable_Diem.getColumnModel().getColumn(0).setResizable(false);
            jTable_Diem.getColumnModel().getColumn(1).setResizable(false);
            jTable_Diem.getColumnModel().getColumn(2).setResizable(false);
            jTable_Diem.getColumnModel().getColumn(3).setResizable(false);
            jTable_Diem.getColumnModel().getColumn(4).setResizable(false);
            jTable_Diem.getColumnModel().getColumn(5).setResizable(false);
        }

        jScrollPane9.setViewportView(jScrollPane8);

        jButton_suaDiem.setText("Sửa điểm");

        jButton_xoaDiem.setText("Xoá điểm");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel5)
                        .addGap(115, 115, 115)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jButton_timKiemDiem))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_suaDiem)
                    .addComponent(jButton_themMoiDiem)
                    .addComponent(jButton_xoaDiem))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_timKiemDiem)
                    .addComponent(jButton_themMoiDiem))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButton_suaDiem)
                        .addGap(74, 74, 74)
                        .addComponent(jButton_xoaDiem)
                        .addGap(0, 313, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("QL Điểm", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_xoaGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xoaGiangVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_xoaGiangVienActionPerformed

    private void jButton_themMoiSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_themMoiSinhVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_themMoiSinhVienActionPerformed

    private void jButton_timKiemHocPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_timKiemHocPhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_timKiemHocPhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    public void hienThiSinhVien() {
        ArrayList<SinhVien> listSinhVien = this.adminController.hienThiSinhVien();
        DefaultTableModel model = (DefaultTableModel) jTable_SinhVien.getModel();
        model.setRowCount(0);
        for (SinhVien sv : listSinhVien) {
            Object[] row = {
                sv.getMSSV(),
                sv.getHoTen(),
                sv.getGioiTinh(),
                sv.getNgaySinh(),
                sv.getQueQuan(),
                sv.getSDT(),
                sv.getEmail()
            };
            model.addRow(row);
        }
    }

    public void hienThiGiangVien() {
        ArrayList<GiangVien> listGiangVien = this.adminController.hienThiGiangVien();
        DefaultTableModel model = (DefaultTableModel) jTable_GiangVien.getModel();
        model.setRowCount(0);
        for (GiangVien gv : listGiangVien) {
            Object[] row = {
                gv.getMSGV(),
                gv.getHoTen(),
                gv.getGioiTinh(),
                gv.getNgaySinh(),
                gv.getQueQuan(),
                gv.getSDT(),
                gv.getEmail()
            };
            model.addRow(row);
        }
    }

    public void hienThiDiem() {
        ArrayList<Diem> listDiem = this.adminController.hienThiDiem();
        DefaultTableModel model = (DefaultTableModel) jTable_Diem.getModel();
        model.setRowCount(0);
        for (Diem diem : listDiem) {
            Object[] row = {
                diem.getMaLop(),
                diem.getMaHP(),
                diem.getMSSV(),
                diem.getDiemQT(),
                diem.getDiemCK(),
                diem.getTrongSoQT()
            };
            model.addRow(row);
        }
    }

    public void hienThiLopHoc() {
        ArrayList<LopHoc> listLopHoc = this.adminController.hienThiLopHoc();
        DefaultTableModel model = (DefaultTableModel) jTable_LopHoc.getModel();
        model.setRowCount(0);
        for (LopHoc lopHoc : listLopHoc) {
            Object[] row = {
                lopHoc.getMaLop(),
                lopHoc.getMaHP(),
                lopHoc.getMSGV(),
                lopHoc.getPhongHoc(),
                lopHoc.getThoiGian()
            };
            model.addRow(row);
        }
    }

    public void hienThiHocPhan() {
        ArrayList<HocPhan> listHocPhan = this.adminController.hienThiHocPhan();
        DefaultTableModel model = (DefaultTableModel) jTable_HocPhan.getModel();
        model.setRowCount(0);
        for (HocPhan hocPhan : listHocPhan) {
            Object[] row = {
                hocPhan.getMaHP(),
                hocPhan.getTenHP(),
                hocPhan.getSoTinChi()
            };
            model.addRow(row);
        }
    }

    private AdminController adminController;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_suaDiem;
    private javax.swing.JButton jButton_suaGiangVien;
    private javax.swing.JButton jButton_suaHocPhan;
    private javax.swing.JButton jButton_suaLopHoc;
    private javax.swing.JButton jButton_suaSinhVien;
    private javax.swing.JButton jButton_themMoiDiem;
    private javax.swing.JButton jButton_themMoiGiangVien;
    private javax.swing.JButton jButton_themMoiHocPhan;
    private javax.swing.JButton jButton_themMoiLopHoc;
    private javax.swing.JButton jButton_themMoiSinhVien;
    private javax.swing.JButton jButton_timKiemDiem;
    private javax.swing.JButton jButton_timKiemGiangVien;
    private javax.swing.JButton jButton_timKiemHocPhan;
    private javax.swing.JButton jButton_timKiemLopHoc;
    private javax.swing.JButton jButton_timKiemSinhVien;
    private javax.swing.JButton jButton_xoaDiem;
    private javax.swing.JButton jButton_xoaGiangVien;
    private javax.swing.JButton jButton_xoaHocPhan;
    private javax.swing.JButton jButton_xoaLopHoc;
    private javax.swing.JButton jButton_xoaSinhVien;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_Diem;
    private javax.swing.JTable jTable_GiangVien;
    private javax.swing.JTable jTable_HocPhan;
    private javax.swing.JTable jTable_LopHoc;
    private javax.swing.JTable jTable_SinhVien;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    public JTable getjTable_Diem() {
        return jTable_Diem;
    }

    public void setjTable_Diem(JTable jTable_Diem) {
        this.jTable_Diem = jTable_Diem;
    }

    public JTable getjTable_GiangVien() {
        return jTable_GiangVien;
    }

    public void setjTable_GiangVien(JTable jTable_GiangVien) {
        this.jTable_GiangVien = jTable_GiangVien;
    }

    public JTable getjTable_HocPhan() {
        return jTable_HocPhan;
    }

    public void setjTable_HocPhan(JTable jTable_HocPhan) {
        this.jTable_HocPhan = jTable_HocPhan;
    }

    public JTable getjTable_LopHoc() {
        return jTable_LopHoc;
    }

    public void setjTable_LopHoc(JTable jTable_LopHoc) {
        this.jTable_LopHoc = jTable_LopHoc;
    }

    public JTable getjTable_SinhVien() {
        return jTable_SinhVien;
    }

    public void setjTable_SinhVien(JTable jTable_SinhVien) {
        this.jTable_SinhVien = jTable_SinhVien;
    }

    
}
